#!/usr/bin/env sage

n = 123
m = 42

K.<a> = GF(256, modulus=[1,1,0,1,1,0,0,0,1])

R = PolynomialRing(K, n, 'x')

################################################################

ks = [tuple((i,j).count(u) for u in range(n)) for i in range(n) for j in range(i,n-m)]
ks += [tuple(i == u for u in range(n)) for i in range(n)]  + [(0,)*n]

F = []
for _ in range(m):
    F.append(R({k: K.random_element() for k in ks}))

T = matrix(GL(n,K).random_element())

################################################################

ks = [tuple(j == i for j in range(n)) for i in range(n)]

P = []
for f in F:
    P.append(f(*(R({k: t for k,t in zip(ks, ts)}) for ts in T)))

################################################################

print('# generated by ./generate.sage')
print('from sage.all import *')
print(f"K = GF({K.cardinality()}, 'a', modulus={str(list(K.modulus())).replace(' ','')})")
print(f"R = PolynomialRing(K, {n}, 'x')")

mons = {t for f in P for t in f.dict()}
mons = sorted(mons)
print('M = [')
for t in mons:
    print(f'{" "*8} {str(t).replace(" ","")},')
print('    ]')

print('I = K.from_integer')
print('P = [')
for f in P:
    s = [f'M[{mons.index(t)}]: I({c.to_integer():#04x})' for t,c in f.dict().items()]
    print(f'{" "*8}R({{{", ".join(s)}}}),')
print(f']')

################################################################

