<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>InsecureVault</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>netcoreapp8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="banner.png" />
    <None Remove="dbmanager.baml" />
    <None Remove="mainwindow.baml" />
    <EmbeddedResource Include="banner.png" LogicalName="banner.png" />
    <EmbeddedResource Include="dbmanager.baml" LogicalName="dbmanager.baml" />
    <EmbeddedResource Include="mainwindow.baml" LogicalName="mainwindow.baml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="Npgsql">
      <HintPath>../InsecureVault/Npgsql.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>